### ISSUE TITLE
Improve speed of crypto operations

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-drynx#11]
Current main problem with crypto is speed: to decode the numbers, the javascript needs to brute-force the discreet log problem, which takes very long.

- filling a table with 1250 elements takes 5s
- comparing two points takes very long (70% of the time)
- for variance, each values is squared. So for 30 points with numbers 0..6, it needs 1250 elements
- use lattigo to replace pohlig-hellman encryption

How to improve speed?

**Comment by tharvik** [comment]
* kyber in wasm: will take much time
* offload the computation to a trusted server (which would be hosted inside the client's infrastructure)

**Comment by ineiti** [comment]
Will use wasm for lattigo
