### ISSUE TITLE
check if possible to simplify graph for linear regression

### ISSUE THREAD

**Issue by tharvik** [c4dt/service-drynx#18]
When using linear regression, we actually receive the factor of a polynome of degree d, which we interpolate. It would be faster to only compute the borders, but hovering and seeing the values is needed. See if plotly allows that.

**Comment by tharvik** [comment]
Doesn't look like there is an easy way to do so; we can maybe handle the zooming event and add precision when needed. For now, putting it in a (distant) futur.

**Comment by ineiti** [comment]
We should also consider using another plot library...

**Comment by tharvik** [comment]
Looks like there isn't many allowing for 3D visualisation, yet found some
 * plotly.js which we are using now: laggy and not really scaling
 * D3.js with some hack but need much customisation for simple interaction: http://bl.ocks.org/supereggbert/aff58196188816576af0
 * vis.js which looks like the best option, will try to spick with it: https://visjs.github.io/vis-graph3d/examples/

**Comment by cgrigis** [comment]
How about [MathBox](https://github.com/unconed/mathbox)? Perhaps overkill?

**Comment by tharvik** [comment]
Hoo, missed this one, it looks nice :)
But on the other hand, it looks abandonned and not much documented
I've actually just finished trying vis.js with @ineiti and it kept its promises; we will go with that.

**Comment by cgrigis** [comment]
> But on the other hand, it looks abandonned and not much documented

Argh, true. (three.js is alive and well though.)

> I've actually just finished trying vis.js with @ineiti and it kept its promises; we will go with that.

Cool. :)

**Comment by tharvik** [comment]
So, vis-graph2d is not really mature for that, reverting to using plotly.js for 2D graphs, vis.js for 3D graphs.
