### ISSUE TITLE
stackblitz complains about missing packages

### ISSUE THREAD

**Issue by tharvik** [c4dt/service-drynx#21]
Somewhere, there is deps not correclty made. Fixes them to allow faster stackblitz use.

> Can't find packages: string_decoder vm

> UNMET PEER DEPENDENCIES
> @typescript-eslint/parser @ ^2.0.0
> moment @ ^2.24.0
> vis-data @ ^6.3.0

**Comment by ineiti** [comment]
Deprecated - will not fix.
