### ISSUE TITLE
make should work on Mac

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-drynx#26]
I wanted to check something, and #25 made me try to download and generate the file myself. But I couldn't do:

```bash
git clone https://github.com/c4dt/service-drynx
cd service-drynx
make
```

Which should `just work (tm)`...

Instead I got:

```log
$ make
Makefile:8: services/mk/service.mk: No such file or directory
git clone -b drynx https://github.com/c4dt/services.git
Cloning into 'services'...
remote: Enumerating objects: 295, done.
remote: Total 295 (delta 0), reused 0 (delta 0), pack-reused 295
Receiving objects: 100% (295/295), 41.26 KiB | 251.00 KiB/s, done.
Resolving deltas: 100% (99/99), done.
services/mk/service.mk:35: /config.mk: No such file or directory
services/mk/service.mk:46: service/library.mk: No such file or directory
services/mk/service.mk:50: service/webapp.mk: No such file or directory
make: *** No rule to make target `service/webapp.mk'.  Stop.
```

**Comment by tharvik** [comment]
Hum, did you try with `gmake`, the GNU one, instead of the BSD one?

**Comment by ineiti** [comment]
no, but I'd like to keep it with 1 make, except if you make a _really_ good case to use `gmake`.

**Comment by tharvik** [comment]
I'll try, can you give your output of `make -v`?

**Comment by ineiti** [comment]
```
$ make -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by tharvik** [comment]
@ineiti it now builds on Mac OS X via travis, does it works on your infra now?

**Comment by ineiti** [comment]
If the three commands given in the issue are correct and should work, then it still doesn't work. I can take the `.travis.yml`  `make library-build library-test webapp-build webapp/dist/stackblitz` and get it to run, but not with a simple `make`...

**Comment by tharvik** [comment]
@ineiti master is passing on Mac OS X now :)

**Comment by ineiti** [comment]
I still get one error/warning at the very beginning:

```bash
[ligasser@mbp ~/Programming/C4DT/service-drynx (master)]$ make
Makefile:8: services/mk/service.mk: No such file or directory
```

But after that it continues to the end and fails with the following error:
```
Compiling angular-plotly.js : es2015 as esm2015
Generating ES5 bundles for differential loading...
An unhandled exception occurred: Call retries were exceeded
See "/private/var/folders/7q/t2st7wbs1f780sxd_h3hnygc0000gp/T/ng-CEfeVI/angular-errors.log" for further details.
make: *** [webapp-build] Error 127
```

This is with node v10, trying now with node v12...

**Comment by tharvik** [comment]
> I still get one error/warning at the very beginning:
> 
> ```shell
> [ligasser@mbp ~/Programming/C4DT/service-drynx (master)]$ make
> Makefile:8: services/mk/service.mk: No such file or directory
> ```

That's normal behavior, it's just `make` warning that there is a missing file to include which it then get via `git clone https://github.com/c4dt/services`.

> But after that it continues to the end and fails with the following error:
> 
> ```
> Compiling angular-plotly.js : es2015 as esm2015
> Generating ES5 bundles for differential loading...
> An unhandled exception occurred: Call retries were exceeded
> See "/private/var/folders/7q/t2st7wbs1f780sxd_h3hnygc0000gp/T/ng-CEfeVI/angular-errors.log" for further details.
> make: *** [webapp-build] Error 127
> ```
> 
> This is with node v10, trying now with node v12...

Arf, that's one of the issue I encountered but was unable to fix when updating the deps. I bailed out because I couldn't find any good information about it; if you have any fix/workaround, I'll gladly apply it! FYI, I'm running net-libs/nodejs-14.4.0, hopefully that'll solve it.

**Comment by ineiti** [comment]
node v12 works - might want to add a test in the makefile for poor people like me ;)
