### ISSUE TITLE
Login fails on first time

### ISSUE THREAD

**Issue by ineiti** [c4dt/service-drynx#27]
On some machines, the following URL cannot be logged in to:

https://demo.c4dt.org/drynx

only if the `/?ticket...` is deleted from the URL, can the login proceed.

**Comment by tharvik** [comment]
Apache's errors.log when it happens
```
[auth_cas:error] [pid 11:tid 140432948328192] [client 172.20.0.2:32774] MOD_AUTH_CAS: Service Ticket to Cookie map file could not be created: File exists
```

It seems that https://github.com/apereo/mod_auth_cas is failing when creating a ticket twice, which is a rare occuring case, so putting it back to backlog.

See https://github.com/c4dt/traefik-docker/pull/7 for an improvement.

**Comment by ineiti** [comment]
Just in case I want to up my apache-foo to do a correct `RewriteRule`...
